Run a subset of e2e tests against differnt ClickHouse versions
We run tests containing 'test_dummy_only' or 'clickhouse' in their name.
I manually renamed a few dummy-provider-only tests to contain 'test_dummy_only'.
Over time, we can rename additional tests to increase our coverage.

This will test more ClickHouse read/write queries across different
ClickHouse versions

diff --git a/.github/workflows/general.yml b/.github/workflows/general.yml
--- a/.github/workflows/general.yml
+++ b/.github/workflows/general.yml
@@ -211,6 +211,49 @@ jobs:
         working-directory: ui
         run: pnpm run typecheck
 
+
+  clickhouse-tests:
+    # We don't run many tests here, so use a normal runner with Github Actions caching
+    # to avoid unnecessarily using Namespace credits (it should still always finish before
+    # the main 'validate' job)
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        clickhouse_version: ["24.12-alpine", "25.2-alpine", "latest-alpine"]
+
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: dtolnay/rust-toolchain@stable
+      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
+      - name: Install cargo-nextest
+        uses: taiki-e/install-action@37bdc826eaedac215f638a96472df572feab0f9b
+        with:
+          tool: cargo-nextest
+
+      - name: Set up TENSORZERO_CLICKHOUSE_URL for E2E tests
+        run: |
+          echo "TENSORZERO_CLICKHOUSE_URL=http://chuser:chpassword@localhost:8123/tensorzero_e2e_tests" >> $GITHUB_ENV
+      
+      # We run this as a separate step so that we can see live build logs
+      # (and fail the job immediately if the build fails)
+      - name: Build the gateway for E2E tests
+        run: cargo build-e2e
+      - name: Launch the gateway for E2E tests
+        run: |
+          TENSORZERO_E2E_PROXY="http://localhost:3003" cargo run-e2e > e2e_logs.txt 2>&1 &
+          while ! curl -s -f http://localhost:3000/health >/dev/null 2>&1; do
+            echo "Waiting for gateway to be healthy..."
+            sleep 1
+          done
+          echo "GATEWAY_PID=$!" >> $GITHUB_ENV
+
+      - name: Test (Rust)
+        run: cargo test-e2e-no-creds
+
+      - name: Print e2e logs
+        if: always()
+        run: cat e2e_logs.txt
+
   ui-tests:
     runs-on: ubuntu-latest
     strategy:
